version: '3'


tasks:
  build: 
    env:
      GOOS: linux
      GOARCH: amd64
    dir: ./
    cmds: 
      - go build -o bootstrap ./cmd/main.go

  bundle:
    dir: ./
    cmds:
      - zip -r blog.zip bootstrap views/ static/

  deploy:
    dir: ./deploy/
    cmds:
      - task: build
      - task: bundle
      - cdk deploy
